### ISSUE TITLE
Issue with tabbing in single page components.

### ISSUE THREAD

**Issue by pgould94** [bootcamp-project-3/Project-3#89]
Some of the single page components are not generating their tabbed content correctly. The equipment page renders 2 posts on the first tab and 2 posts on a second tab when it should be rendering at least 10 posts on the first tab before generating a second. This issue exists on carpool as well.

**Comment by Draekus** [comment]
This issue has been solved. Components were filtering at multiple levels and some components were not filtering correctly because of this. The single page components now only filter for category at the top level.
